version: "3"

services:
  # MySQL
  db:
    platform: linux/x86_64
    container_name: "db"
    # path配下のDockerfile読み込み
    build: ./docker/mysql
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: password # ルートパスワード
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./docker/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./log/mysql:/var/log/mysql # ログの保存
    networks:
      - local-net

  #minio:
    #image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    #container_name: minio
    #ports:
    #  - 9090:9000
    #environment:
    #  - MINIO_ACCESS_KEY=minio
    #  - MINIO_SECRET_KEY=minio123
    #entrypoint: sh
    #command: -c "
    #  mkdir -p /data/.minio.sys/buckets;
    #  cp -r /policies/* /data/.minio.sys/;
    #  cp -r /export/* /data/;
    #  /opt/bin/minio server /data"
    #volumes:
    #  - ./docker/minio:/data
    #  - ./docker/minio/export:/export
    #  - ./docker/minio/policies:/policies
    #command: server /data
    #volumes: 
    # - ./volumes/minio:/data
  s3:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: my-s3
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - ./volumes/minio:/data
      - ./docker/minio/policies:/policies
    ports:
      - "9000:9000"
    command: ["--compat", "server", "/data"]

  # FastAPI
  api:
    platform: linux/x86_64
    # db起動後に立ち上げる
    links:
      - db
      - s3
    container_name: "api"
    # path配下のDockerfile読み込み
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge
